---
title: "introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
# Check if running on GitHub Actions
# This is important as otherwise Github will attempt to build this and it's missing the python libraries and will fail
on_github <- Sys.getenv("GITHUB_ACTIONS") == "true"

   
# If on GitHub, set eval = FALSE for all subsequent chunks
knitr::opts_chunk$set(eval = !on_github)

```

## PLACEHOLDER - to be completed. 
Rcpp examples etc
## Multivariate Normal density
$$
 f(\mathbf{x}) = \frac{1}{(2\pi)^{N/2} |\Sigma|^{1/2}} \exp!\left(-\frac{1}{2}(\mathbf{x}-\boldsymbol{\mu})^\top
  \Sigma^{-1} (\mathbf{x}-\boldsymbol{\mu})\right)
$$


N — dimension

$\mu$ — mean vector (N × 1)

$\Sigma$ — covariance matrix (sN × N)

$\mid\Sigma\mid$ — determinant of Σ

$(\mathbf{x}-\boldsymbol{\mu})^\top \Sigma^{-1} (\mathbf{x}-\boldsymbol{\mu})$ — the Mahalanobis distance (scalar)

```{r setup, include=TRUE,eval=TRUE}
library(vegasr)
vegas_initialize()
library(mvtnorm)
mu<-matrix(c(0.5, -0.2, 0.1),nrow=1)
cov<-matrix(data=c(
                 1.0, 0.5, 0.2,
                 0.5, 1.2, 0.3,
                 0.2, 0.3, 0.8),ncol=3,byrow=FALSE)

myf<-function(x,mu,cov){
  res<-dmvnorm(x,mean = mu,sigma=cov)
  return(res)
  }

########### Estimate integal using defaults
########### cleanstart erases any previous results and grid
result<-vegas(f=myf,
                        lower=c(-5,-5,-5), upper=c(5,5,5),
                        nitn_warm = 10, neval_warm = 10000,
                        nitn = 10, neval = 10000,
                        errTol=0.1,maxIter=20,
                        extra_args=list(mu=mu,cov=cov))
print(result)
#cat("Estimate = ",result$mean," error = ",result$error,"\n")

########### Estimate 5-D integral with known value as check

alpha<-matrix(data=c(1.),nrow=1)
erf<-function(x){return(2 * pnorm(x * sqrt(2)) - 1)}
oneD<-sqrt(pi / alpha[1]) * erf(sqrt(alpha[1]) / 2.0)
true.val<-oneD**5
print(true.val)

gaus<-function(x,alpha){
  # x shape is (batch, dim)
  # Compute sum of squared differences from 0.5
  dx2 = apply((x-0.5)**2,1,sum)
  return(exp(-alpha[1] * dx2))
}
myx<-matrix(data=rep(0.7,10),ncol=5) # 2 row 5 col
gaus(x=myx,alpha=alpha)

result2<-vegas(f=gaus,
                        lower=rep(0,5), upper=rep(1,5),
                        nitn_warm = 10, neval_warm = 10000,
                        nitn = 5, neval = 10000,
                        errTol=0.01,maxIter=100,
                        extra_args=list(alpha=alpha))
print(result2)

```
