---
title: "Using Rcpp in Vegasr"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Using Rcpp in Vegasr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

# Check if running on GitHub Actions
# This is important as otherwise Github will attempt to build this and it's missing the python libraries and will fail
on_github <- Sys.getenv("GITHUB_ACTIONS") == "true"

   
# If on GitHub, set eval = FALSE for all subsequent chunks
knitr::opts_chunk$set(eval = !on_github)

```

```{r cran_check_setting,include=FALSE,eval=TRUE}
# this is to de-tune all examples to get past cran checks
is_checking <- nzchar(Sys.getenv("_R_CHECK_PACKAGE_NAME_"))
if (is_checking) {
     n_cores <- 2 # number of cores for computing marginal density on cran
     no_den_pts<-5 # very ligth grid for on cran
    } else { # running locally to go higher
    n_cores <- parallel::detectCores() - 1
    no_den_pts=50
}

```

### Quickstart
11th-May-update: An example of how to use RcppArmadillo to compute an integrand, which is typically much faster than using R directly. This compares the R function and the Rcpp function each passed to vegas.  

## Model Formulation


### Data set

```{r datasets, include=TRUE,eval=TRUE}
library(vegasr)
vegas_initialize()
thedata<-vegasr:::fn_create_data_1(99999) # a list of y and treat as matrices
# this function is in vegasr/R/fn_internal.R
```

```{r logpos,include=TRUE,eval=TRUE}
### Now use VEGAS
library(RcppArmadillo)

theta<- matrix(data=rep(0.1,length=4*6), ncol = 6)

vegasr:::fn_log_post_1(theta, thedata$y, thedata$treat,.0, 1.0)
# this function is in vegasr/R/fn_internal.R

vegasr::arma_fn_log_post_1(theta, thedata$y, thedata$treat,0.0, 1.0)
# this function is in vegasr/src/fns.cpp

```
```{r logpos2,include=TRUE,eval=TRUE}
library(vegasr)
# now setup python environment
vegas_initialize() # this needed called once per session after library(vegas)
library(tictoc)


tic()
result_logEv<-vegasBayesEvidence(f=vegasr:::fn_log_post_1,
                                 lower=c(-1,-1,-1,-1,0.0001,0.0001),
                                 upper=c(1,1,1,1,1,1),
                                 nitn_warm = 5, neval_warm = 1e5,
                                 nitn = 5, neval = 1e5,
                                 errTol=0.1,maxIter=10,seed=99999,nsearch=10000,
                                 extra_args=list(
                                   y=thedata$y,treat=thedata$treat,shiftby=0,uselog=1.))
toc()
cat("log evidence = ",result_logEv,"\n")


tic()
result_logEv<-vegasBayesEvidence(f=arma_fn_log_post_1,
                                 lower=c(-1,-1,-1,-1,0.0001,0.0001),
                                 upper=c(1,1,1,1,1,1),
                                 nitn_warm = 5, neval_warm = 1e5,
                                 nitn = 5, neval = 1e5,
                                 errTol=0.1,maxIter=10,seed=99999,nsearch=10000,
                                 extra_args=list(
                                   y=thedata$y,treat=thedata$treat,shiftby=0,uselog=1.))
toc()
cat("log evidence = ",result_logEv,"\n")

```


