// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// arma_fn_log_post_1
arma::vec arma_fn_log_post_1(const arma::mat& theta, const arma::vec& y, const arma::vec& treat, double shiftby, double uselog);
RcppExport SEXP _vegasr_arma_fn_log_post_1(SEXP thetaSEXP, SEXP ySEXP, SEXP treatSEXP, SEXP shiftbySEXP, SEXP uselogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type shiftby(shiftbySEXP);
    Rcpp::traits::input_parameter< double >::type uselog(uselogSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_fn_log_post_1(theta, y, treat, shiftby, uselog));
    return rcpp_result_gen;
END_RCPP
}
// eigen_fn_log_post_1
Eigen::VectorXd eigen_fn_log_post_1(const Eigen::MatrixXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& treat, double shiftby, double uselog);
RcppExport SEXP _vegasr_eigen_fn_log_post_1(SEXP thetaSEXP, SEXP ySEXP, SEXP treatSEXP, SEXP shiftbySEXP, SEXP uselogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type shiftby(shiftbySEXP);
    Rcpp::traits::input_parameter< double >::type uselog(uselogSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_fn_log_post_1(theta, y, treat, shiftby, uselog));
    return rcpp_result_gen;
END_RCPP
}
// eigen_fn_log_post_1_par
Eigen::VectorXd eigen_fn_log_post_1_par(const Eigen::MatrixXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& treat, double shiftby, double uselog);
RcppExport SEXP _vegasr_eigen_fn_log_post_1_par(SEXP thetaSEXP, SEXP ySEXP, SEXP treatSEXP, SEXP shiftbySEXP, SEXP uselogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type shiftby(shiftbySEXP);
    Rcpp::traits::input_parameter< double >::type uselog(uselogSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_fn_log_post_1_par(theta, y, treat, shiftby, uselog));
    return rcpp_result_gen;
END_RCPP
}
// eigen_fn_marg_1
Eigen::VectorXd eigen_fn_marg_1(const Eigen::MatrixXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& treat, double shiftby, double uselog, double z);
RcppExport SEXP _vegasr_eigen_fn_marg_1(SEXP thetaSEXP, SEXP ySEXP, SEXP treatSEXP, SEXP shiftbySEXP, SEXP uselogSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type shiftby(shiftbySEXP);
    Rcpp::traits::input_parameter< double >::type uselog(uselogSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_fn_marg_1(theta, y, treat, shiftby, uselog, z));
    return rcpp_result_gen;
END_RCPP
}
// eigen_fn_log_post_2
Eigen::VectorXd eigen_fn_log_post_2(const Eigen::MatrixXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& treat, const Eigen::VectorXd& basket, double shiftby, double uselog);
RcppExport SEXP _vegasr_eigen_fn_log_post_2(SEXP thetaSEXP, SEXP ySEXP, SEXP treatSEXP, SEXP basketSEXP, SEXP shiftbySEXP, SEXP uselogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type basket(basketSEXP);
    Rcpp::traits::input_parameter< double >::type shiftby(shiftbySEXP);
    Rcpp::traits::input_parameter< double >::type uselog(uselogSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_fn_log_post_2(theta, y, treat, basket, shiftby, uselog));
    return rcpp_result_gen;
END_RCPP
}
// eigen_fn_log_post_2_par
Eigen::VectorXd eigen_fn_log_post_2_par(const Eigen::MatrixXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& treat, const Eigen::VectorXd& basket, double shiftby, double uselog);
RcppExport SEXP _vegasr_eigen_fn_log_post_2_par(SEXP thetaSEXP, SEXP ySEXP, SEXP treatSEXP, SEXP basketSEXP, SEXP shiftbySEXP, SEXP uselogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type basket(basketSEXP);
    Rcpp::traits::input_parameter< double >::type shiftby(shiftbySEXP);
    Rcpp::traits::input_parameter< double >::type uselog(uselogSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_fn_log_post_2_par(theta, y, treat, basket, shiftby, uselog));
    return rcpp_result_gen;
END_RCPP
}
// eigen_fn_marg_2
Eigen::VectorXd eigen_fn_marg_2(const Eigen::MatrixXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& treat, const Eigen::VectorXd& basket, double shiftby, double uselog, double z);
RcppExport SEXP _vegasr_eigen_fn_marg_2(SEXP thetaSEXP, SEXP ySEXP, SEXP treatSEXP, SEXP basketSEXP, SEXP shiftbySEXP, SEXP uselogSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type basket(basketSEXP);
    Rcpp::traits::input_parameter< double >::type shiftby(shiftbySEXP);
    Rcpp::traits::input_parameter< double >::type uselog(uselogSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_fn_marg_2(theta, y, treat, basket, shiftby, uselog, z));
    return rcpp_result_gen;
END_RCPP
}
// diff_list
Rcpp::List diff_list(const Rcpp::List& grid);
RcppExport SEXP _vegasr_diff_list(SEXP gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type grid(gridSEXP);
    rcpp_result_gen = Rcpp::wrap(diff_list(grid));
    return rcpp_result_gen;
END_RCPP
}
// len_list
Eigen::VectorXd len_list(const Rcpp::List& grid);
RcppExport SEXP _vegasr_len_list(SEXP gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type grid(gridSEXP);
    rcpp_result_gen = Rcpp::wrap(len_list(grid));
    return rcpp_result_gen;
END_RCPP
}
// eigen_grid
void eigen_grid(const Rcpp::List& xgrid, const VectorXd& y);
RcppExport SEXP _vegasr_eigen_grid(SEXP xgridSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type y(ySEXP);
    eigen_grid(xgrid, y);
    return R_NilValue;
END_RCPP
}
// eigen_gridM
Rcpp::List eigen_gridM(const Rcpp::List& xgrid, const Eigen::MatrixXd& y);
RcppExport SEXP _vegasr_eigen_gridM(SEXP xgridSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_gridM(xgrid, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vegasr_arma_fn_log_post_1", (DL_FUNC) &_vegasr_arma_fn_log_post_1, 5},
    {"_vegasr_eigen_fn_log_post_1", (DL_FUNC) &_vegasr_eigen_fn_log_post_1, 5},
    {"_vegasr_eigen_fn_log_post_1_par", (DL_FUNC) &_vegasr_eigen_fn_log_post_1_par, 5},
    {"_vegasr_eigen_fn_marg_1", (DL_FUNC) &_vegasr_eigen_fn_marg_1, 6},
    {"_vegasr_eigen_fn_log_post_2", (DL_FUNC) &_vegasr_eigen_fn_log_post_2, 6},
    {"_vegasr_eigen_fn_log_post_2_par", (DL_FUNC) &_vegasr_eigen_fn_log_post_2_par, 6},
    {"_vegasr_eigen_fn_marg_2", (DL_FUNC) &_vegasr_eigen_fn_marg_2, 7},
    {"_vegasr_diff_list", (DL_FUNC) &_vegasr_diff_list, 1},
    {"_vegasr_len_list", (DL_FUNC) &_vegasr_len_list, 1},
    {"_vegasr_eigen_grid", (DL_FUNC) &_vegasr_eigen_grid, 2},
    {"_vegasr_eigen_gridM", (DL_FUNC) &_vegasr_eigen_gridM, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_vegasr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
