# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate Normal Density (RcppArmadillo)
#'
#' @param x   Matrix of integration variables (BATCH x N)
#' @param mu  Mean vector (length N)
#' @param cov Covariance matrix (N x N)
#' @param a   Scaling factor
#' @return Numeric vector of density values (length BATCH)
#' @export
dmvnorm_arma <- function(x, mu, cov, a) {
    .Call(`_vegasr_dmvnorm_arma`, x, mu, cov, a)
}

