# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Posterior Density Function using RcppArmadillo - Example 1
#'
#' @description An example showing how to write a function for use with \code{\link{vegasBayesEvidence}} for
#' Bayesian computation using the RcppArmadillo library
#' This example function describes a simple Bayesian hierarchical model comprising of a logistic regression with
#' intercept and single binary covariate for treatment effect each with a hierarchical prior.
#' This has six parameters in total.
#'
#' @details The is an example function written using RcppArmadillo and has same functionality as the R function
#' \code{\link{fn_log_post_1}}. It uses a transformation so the density
#' can be integrated across the full domain of each parameter, i.e. the density includes a Jacobian
#'  See \code{vignette("rcpp", package = "vegasr")} for more details. Several helper function are required
#'  specifically normal and half-normal densities are also written in RcppArmadillo. Use Rcpp::sourceCpp()
#'  or similar to run the functions separately. They are in the fns_arma.cpp file in the source package.
#'
#' @title Posterior Density Function using RcppArmadillo - Example 1
#' @name arma_fn_log_post_1
#' @aliases arma_fn_log_post_1
#' @description An example showing how to write a function for use with \code{\link{vegasBayesEvidence}} for
#' Bayesian computation using the RcppArmadillo library.
#' This example function describes a simple Bayesian hierarchical model comprising of a logistic regression with
#' intercept and single binary covariate for treatment effect each with a hierarchical prior.
#' This has six parameters in total. See \code{vignette("rcpp", package = "vegasr")} for Rcpp details.
#'
#' @details The is an example function written using RcppArmadillo and has same functionality as the R function
#' \code{\link{fn_log_post_1}}. It uses a transformation so the density
#' can be integrated across the full domain of each parameter, i.e. the density includes a Jacobian
#'  See \code{vignette("rcpp", package = "vegasr")} for more details. Several helper function are required
#'  specifically normal and half-normal densities are also written in RcppArmadillo.
#'
#' @param theta pass a numerical R matrix of dimension Batch x M, where M is number of parameters, here M=6
#' Batch can be any positive integer
#' @param y a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param treat a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param shiftby a numerical scalar used to help avoid underflow. Used in \code{\link{vegasBayesEvidence}}
#' @param uselog a numerical flag value takes either 1.0 or 0.0 and used to return either log or real scale
#' value. Used in \code{\link{vegasBayesEvidence}}
#' @export
arma_fn_log_post_1 <- function(theta, y, treat, shiftby, uselog) {
    .Call(`_vegasr_arma_fn_log_post_1`, theta, y, treat, shiftby, uselog)
}

#' @title Posterior Density Function using RcppEigen - Example 1
#' @name eigen_fn_log_post_1
#' @aliases eigen_fn_log_post_1
#' @description An example showing how to write a function for use with \code{\link{vegasBayesEvidence}} for
#' Bayesian computation using the RcppEigen library.
#' This example function describes a simple Bayesian hierarchical model comprising of a logistic regression with
#' intercept and single binary covariate for treatment effect each with a hierarchical prior.
#' This has six parameters in total. See \code{vignette("rcpp", package = "vegasr")} for Rcpp details.
#'
#' @details The is an example function written using RcppEigen and has same functionality as the R function
#' \code{\link{fn_log_post_1}}. It uses a transformation so the density
#' can be integrated across the full domain of each parameter, i.e. the density includes a Jacobian
#'  See \code{vignette("rcpp", package = "vegasr")} for more details. Several helper functions are required,
#'  specifically normal and half-normal densities are also written in RcppEigen. Use Rcpp::sourceCpp()
#'  or similar to run the functions separately. They are in the fns_eigen.cpp file in the source package.
#'
#' @param theta pass a numerical R matrix of dimension Batch x M, where M is number of parameters, here M=6,
#' Batch can be any positive integer
#' @param y a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param treat a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param shiftby a numerical scalar used to help avoid underflow. Used in \code{\link{vegasBayesEvidence}}
#' @param uselog a numerical flag value takes either 1.0 or 0.0 and used to return either log or real scale
#' value. Used in \code{\link{vegasBayesEvidence}}
#' @export
eigen_fn_log_post_1 <- function(theta, y, treat, shiftby, uselog) {
    .Call(`_vegasr_eigen_fn_log_post_1`, theta, y, treat, shiftby, uselog)
}

#' @title Posterior Density Function using RcppParallel - Example 1
#' @name eigen_fn_log_post_1_par
#' @aliases eigen_fn_log_post_1_par
#' @description An example showing how to write a function for use with \code{\link{vegasBayesEvidence}} for
#' Bayesian computation using the RcppParallel library
#' This example function describes a simple Bayesian hierarchical model comprising of a logistic regression with
#' intercept and single binary covariate for treatment effect each with a hierarchical prior.
#' This has six parameters in total. See \code{vignette("rcpp", package = "vegasr")} for Rcpp details.
#'
#' @details The is an example function written using RcppParallel and has same functionality as the R function
#' \code{\link{fn_log_post_1}}. It uses a transformation so the density
#' can be integrated across the full domain of each parameter, i.e. the density includes a Jacobian
#'  See \code{vignette("rcpp", package = "vegasr")} for more details. Several helper function are required
#'  specifically normal and half-normal densities are also written in RcppEigen. Use Rcpp::sourceCpp()
#'  or similar to run the functions separately. They are in the fns_eigen.cpp file in the source package.
#'
#' @param theta pass a numerical R matrix of dimension Batch x M, where M is number of parameters, here M=6,
#' Batch can be any positive integer
#' @param y a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param treat a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param shiftby a numerical scalar used to help avoid underflow. Used in \code{\link{vegasBayesEvidence}}
#' @param uselog a numerical flag value takes either 1.0 or 0.0 and used to return either log or real scale
#' value. Used in \code{\link{vegasBayesEvidence}}
#' @export
eigen_fn_log_post_1_par <- function(theta, y, treat, shiftby, uselog) {
    .Call(`_vegasr_eigen_fn_log_post_1_par`, theta, y, treat, shiftby, uselog)
}

#' @title Marginal Posterior Density Function using RcppParallel - Example 1
#' @name eigen_fn_marg_1
#' @aliases eigen_fn_marg_1
#' @description An example showing how to write a function for use with \code{\link{vegasBayesPosterior}} for
#' Bayesian computation. This is almost identical to \code{\link{eigen_fn_log_post_1_par}} but we now reduce the dimension
#' by 1 and pass a fixed value for the missing dimension for the variable whose marginal we want to compute.
#' See \code{vignette("rcpp", package = "vegasr")} for Rcpp details.
#' @details The is an example function written using RcppParallel and has same functionality as the R function
#' \code{\link{fn_marg_1}}. This function is in the fns_eigen.cpp file in the source package.
#'
#' @param theta pass a numerical R matrix of dimension Batch x M, where M is number of parameters, here M=5,
#' Batch can be any positive integer
#' @param y a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param treat a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param shiftby a numerical scalar used to help avoid underflow. Used in \code{\link{vegasBayesPosterior}}
#' @param uselog a numerical flag value takes either 1.0 or 0.0 and used to return either log or real scale
#' value. Used in \code{\link{vegasBayesPosterior}}
#' @param z a numerical and the function call computes the density at this value, i.e. f(z).
#' @export
eigen_fn_marg_1 <- function(theta, y, treat, shiftby, uselog, z) {
    .Call(`_vegasr_eigen_fn_marg_1`, theta, y, treat, shiftby, uselog, z)
}

#' @title Posterior Density Function using RcppEigen - Example 2
#' @name eigen_fn_log_post_2
#' @aliases eigen_fn_log_post_2
#' @description An example showing how to write a function for use with \code{\link{vegasBayesEvidence}} for
#' Bayesian computation using the RcppEigen library
#' This example function describes a Bayesian hierarchical model comprising of a logistic regression with
#' intercept and single binary covariate for treatment effect each with a hierarchical prior.
#' This has 14 parameters in total and is a basket trial with five baskets. See article on package website for details.
#'
#' @details The is an example function written using RcppEigen. It uses a transformation so the density
#' can be integrated across the full domain of each parameter, i.e. the density includes a Jacobian
#'  Several helper function are required
#'  specifically normal and half-normal densities are also written in RcppEigen. Use Rcpp::sourceCpp()
#'  or similar to run the functions separately. They are in the fns_eigen.cpp file in the source package.
#'
#' @param theta pass a numerical R matrix of dimension Batch x M, where M is number of parameters, here M=14,
#' Batch can be any positive integer
#' @param y a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param treat a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param basket a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param shiftby a numerical scalar used to help avoid underflow. Used in \code{\link{vegasBayesEvidence}}
#' @param uselog a numerical flag value takes either 1.0 or 0.0 and used to return either log or real scale
#' value. Used in \code{\link{vegasBayesEvidence}}
#' @export
eigen_fn_log_post_2 <- function(theta, y, treat, basket, shiftby, uselog) {
    .Call(`_vegasr_eigen_fn_log_post_2`, theta, y, treat, basket, shiftby, uselog)
}

#' @title Posterior Density Function using RcppParallel - Example 2
#' @name eigen_fn_log_post_2_par
#' @aliases eigen_fn_log_post_2_par
#' @description An example showing how to write a function for use with \code{\link{vegasBayesEvidence}} for
#' Bayesian computation using the RcppEigen library
#' This example function describes a Bayesian hierarchical model comprising of a logistic regression with
#' intercept and single binary covariate for treatment effect each with a hierarchical prior.
#' This has 14 parameters in total and is a basket trial with five baskets. See article on package website for details.
#'
#' @details The is an example function written using RcppParallel. It uses a transformation so the density
#' can be integrated across the full domain of each parameter, i.e. the density includes a Jacobian
#' See \code{vignette("rcpp", package = "vegasr")} for more details. Several helper function are required
#' specifically normal and half-normal densities are also written in RcppEigen. Use Rcpp::sourceCpp()
#' or similar to run the functions separately. They are in the fns_eigen.cpp file in the source package.
#'
#' @param theta pass a numerical R matrix of dimension Batch x M, where M is number of parameters, here M=14,
#' Batch can be any positive integer
#' @param y a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param treat a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param basket a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param shiftby a numerical scalar used to help avoid underflow. Used in \code{\link{vegasBayesEvidence}}
#' @param uselog a numerical flag value takes either 1.0 or 0.0 and used to return either log or real scale
#' value. Used in \code{\link{vegasBayesEvidence}}
#' @export
eigen_fn_log_post_2_par <- function(theta, y, treat, basket, shiftby, uselog) {
    .Call(`_vegasr_eigen_fn_log_post_2_par`, theta, y, treat, basket, shiftby, uselog)
}

#' @title Parallel Marginal Example 2
#' @name eigen_fn_marg_2
#' @aliases eigen_fn_marg_2
#' @description An example showing how to write a function for use with \code{\link{vegasBayesEvidence}} for
#' Bayesian computation using the RcppParallel library. This is similar to \code{\link{eigen_fn_log_post_2_par}}
#' but we now reduce the dimension by 1 and pass a fixed value for the missing dimension for the variable whose
#' marginal we want to compute.
#' This example function describes a Bayesian hierarchical model comprising of a logistic regression with
#' intercept and single binary covariate for treatment effect each with a hierarchical prior.
#' This has 14 parameters in total and is a basket trial with five baskets. See article on package website for details.
#'
#' @details The is an example function written using RcppParallel. It uses a transformation so the density
#' can be integrated across the full domain of each parameter, i.e. the density includes a Jacobian
#'  See \code{vignette("rcpp", package = "vegasr")} for more details. Several helper function are required
#'  specifically normal and half-normal densities are also written in RcppEigen. Use Rcpp::sourceCpp()
#'  or similar to run the functions separately. They are in the fns_eigen.cpp file in the source package.
#'
#' @param theta pass a numerical R matrix of dimension Batch x M, where M is number of parameters, here M=6
#' Batch can be any positive integer
#' @param y a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param treat a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param basket a numeric R matrix of dimension N x 1, this is the response variable and should be 1.0 or 0.0
#' entries only
#' @param shiftby a numerical scalar used to help avoid underflow. Used in \code{\link{vegasBayesEvidence}}
#' @param uselog a numerical flag value takes either 1.0 or 0.0 and used to return either log or real scale
#' value. Used in \code{\link{vegasBayesEvidence}}
#' @param z a numerical and the function call computes the density at this value, i.e. f(z).
#' @export
eigen_fn_marg_2 <- function(theta, y, treat, basket, shiftby, uselog, z) {
    .Call(`_vegasr_eigen_fn_marg_2`, theta, y, treat, basket, shiftby, uselog, z)
}

